"""
Review memo generator — takes extracted clauses and produces a formatted memo
that associates review instead of the raw contract.
Same rigour, fraction of the time.
"""
import anthropic
from config import get_settings
import structlog

log = structlog.get_logger()

_MEMO_SYSTEM = """You are a senior Nigerian commercial lawyer writing a review memo for a partner or senior associate.
Your memos are precise, well-structured, and immediately actionable.
You write in clear professional English — no legalese unless quoting the contract directly.
Partners trust your memos to make decisions without reading the raw contract."""

RISK_EMOJI = {"low": "🟢", "medium": "🟡", "high": "🔴", "critical": "🚨"}


def generate_memo(
    filename: str,
    clauses: dict,
    firm_name: str = "",
) -> str:
    """
    Generate a structured review memo from extracted clauses.
    Returns the memo as a formatted string (markdown).
    """
    client = anthropic.Anthropic(api_key=get_settings().anthropic_api_key)

    overall_risk  = clauses.get("overall_risk", "unknown")
    overall_summary = clauses.get("overall_summary", "")
    red_flags     = clauses.get("red_flags", [])

    # Build clause summary for prompt
    clause_lines = []
    for cat in [
        "parties", "effective_date_and_term", "payment_terms", "termination",
        "liability_and_indemnity", "intellectual_property", "confidentiality",
        "governing_law_and_jurisdiction", "dispute_resolution", "force_majeure",
        "representations_and_warranties",
    ]:
        c = clauses.get(cat)
        if not c or not isinstance(c, dict):
            continue
        label = cat.replace("_", " ").title()
        risk  = c.get("risk_level", "low")
        emoji = RISK_EMOJI.get(risk, "⚪")
        summary = c.get("summary", "Not found")
        quote   = c.get("exact_quote", "")
        note    = c.get("risk_note", "")
        line = f"**{label}** {emoji} ({risk.upper()})\n{summary}"
        if quote:
            line += f'\n> "{quote}"'
        if note:
            line += f"\n⚠️ {note}"
        clause_lines.append(line)

    red_flag_text = ""
    if red_flags:
        red_flag_text = "\n\n**RED FLAGS:**\n" + "\n".join(f"• {f}" for f in red_flags)

    prompt = f"""Write a professional contract review memo for {firm_name or "the firm"}.

Document: {filename}
Overall Risk: {overall_risk.upper()} {RISK_EMOJI.get(overall_risk, "")}
Summary: {overall_summary}

Extracted clauses:
{"---".join(clause_lines)}
{red_flag_text}

Write the memo in this exact structure:

# CONTRACT REVIEW MEMO
**Document:** [filename]
**Prepared by:** Digital Associates AI
**Risk Rating:** [overall risk with emoji]

## Executive Summary
[2-3 sentences on what this contract is and the key risk posture]

## Key Terms
[Bullet point summary of parties, term, payment — the essentials a partner checks first]

## Clause Analysis
[For each clause found: one paragraph, plain English, flag risks clearly]

## Red Flags
[Numbered list of the most important concerns — be specific, cite clauses]

## Recommended Actions
[3-5 numbered action items for the reviewing associate or partner]

---
*This memo was generated by Digital Associates AI and should be reviewed by a qualified legal professional before reliance.*

Keep it tight — this memo should save the associate 2 hours, not add to their reading pile."""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        system=_MEMO_SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )

    memo = response.content[0].text.strip()
    log.info("memo_generated", filename=filename, firm=firm_name)
    return memo
